/**
 * Turns web/art/*.png into web/art.ts — a map of card id to an inlined WebP
 * data URI.
 *
 * The page ships as a single self-contained file, so the art travels with it.
 * 320px is well above the size any card is drawn at, and each image lands at
 * roughly eight kilobytes.
 */

import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const artDir = resolve(here, 'art');

const ids = readdirSync(artDir)
  .filter((name) => name.endsWith('.png'))
  .map((name) => name.slice(0, -4))
  .sort();

const script = `
import sys, io, base64
from PIL import Image
out = {}
for path, key in zip(sys.argv[1::2], sys.argv[2::2]):
    im = Image.open(path).convert('RGB').resize((320, 320), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, 'WEBP', quality=76, method=6)
    out[key] = base64.b64encode(buf.getvalue()).decode('ascii')
import json; print(json.dumps(out))
`;

const args = ids.flatMap((id) => [join(artDir, `${id}.png`), id]);
const json = execFileSync('python3', ['-c', script, ...args], {
  maxBuffer: 256 * 1024 * 1024,
  encoding: 'utf8',
});
const encoded = JSON.parse(json);

const entries = ids
  .map((id) => `  ${JSON.stringify(id)}: 'data:image/webp;base64,${encoded[id]}',`)
  .join('\n');

const file = `/**
 * Card art, inlined as data URIs.
 *
 * Generated by \`npm run art\` from the source images in \`web/art/\`. The page
 * is published as a single file, so the art has to travel inside it.
 *
 * Do not edit by hand.
 */

export const ART: Readonly<Record<string, string>> = {
${entries}
};
`;

writeFileSync(resolve(here, 'art.ts'), file, 'utf8');
const kb = (Buffer.byteLength(file, 'utf8') / 1024).toFixed(0);
console.log(`web/art.ts  ${ids.length} images, ${kb} kB`);
